import fs from 'node:fs'
import lualsSpecs from './coc-luals.json' with { type: 'json' }
import packageJson from './package.json' with { type: 'json' }

const overrides = {
  'Lua.hint.enable': {
    default: true,
  },
  'Lua.misc.parameters': {
    default: [],
    markdownDescription:
      'Additional command line parameters when starting the language service.',
  },
  'Lua.misc.executablePath': {
    markdownDescription: 'Specify the executable path.',
  },
}

// Skip unsupported upstream settings
const ignoredConfigs = ['addonManager', 'addonRepositoryPath']

function generateMarkdown(config) {
  const lines = [
    '<!-- Generated by update-config.js. Do not edit directly. -->',
    '',
    '# Settings Reference',
    '',
    'Configuration options supported by `coc-luals`. Configure them in `coc-settings.json` (`:CocConfig`).',
    '',
    '- Upstream schema: [schema.json](https://github.com/LuaLS/vscode-lua/blob/master/setting/schema.json)',
    '- Extension-specific settings: [coc-luals.json](./coc-luals.json)',
    '- Hint: Auto-completion is available for all keys and enum values in `:CocConfig`',
    '',
    '---',
    '',
  ]

  for (const [key, v] of Object.entries(config)) {
    lines.push(
      `## \`${key}\``,
      `- type: \`${v.type}\``,
      `- default: \`${JSON.stringify(v.default)}\``,
      `- description:    ${v.description || v.markdownDescription || ''}`,
      '',
    )
  }

  return `${lines.join('\n')}\n`
}

async function main() {
  const resp = await fetch(
    'https://github.com/LuaLS/vscode-lua/raw/refs/heads/master/setting/schema.json',
  )
  const schema = await resp.json()
  const properties = schema.properties

  const config = { ...lualsSpecs.configuration }

  // merge config
  console.log('merge config')
  for (const [k, prop] of Object.entries(properties)) {
    if (ignoredConfigs.some(i => k.startsWith(i))) continue
    if (k.includes('.') || !prop.properties) {
      config[`Lua.${k}`] = prop
    }
  }

  for (const [key, override] of Object.entries(overrides)) {
    config[key] = { ...config[key], ...override }
  }

  // write package.json
  console.log('write package.json')
  packageJson.contributes.configuration.properties = config
  packageJson.contributes.commands = lualsSpecs.commands
  fs.writeFileSync('./package.json', `${JSON.stringify(packageJson, null, 2)}\n`)

  // write settings.md
  console.log('write settings.md')
  fs.writeFileSync('./settings.md', generateMarkdown(config))
}

main()
